version: '3'

services:
  backend:
    container_name: freeda-backend 
    build:
      context: ./backend
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /run/user/1000/pulse:/run/pulse:ro
      - ./backend/sounds:/app/sounds
    environment:
      PULSE_SERVER: unix:/run/user/1000/pulse/native
      PULSE_COOKIE: /run/pulse/cookie
    devices:
      - /dev/snd
    networks:
      - my-network
      
  frontend:
    container_name: freeda-frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://${BACKEND_HOST}:5000
    ports:
      - "3000:3000"
    restart: always
    networks:
      - my-network
    env_file:
      - .env

networks:
  my-network:
    driver: bridge
